#ifndef CONSTANTS_H
# define CONSTANTS_H

# define DESCRIPTOR 0

# define SEPARATOR_STRSPLIT ' '

# define START_ROOM_MODIFIER 1
# define END_ROOM_MODIFIER 2

# define START_PATH_NUMBER -1
# define PATH_NUMBER_CLOSE -2
# define START_ROOM_NUMBER 0
# define END_ROOM_NUMBER -1

#endif
